------------------------------------------------------------------
-- SEQUENCES — auto-increment IDs for all tables
-- Run AFTER creating tables (01_schema.sql)
-- Usage: INSERT ... VALUES (SEQ_CUSTOMERS.NEXTVAL, ...)
------------------------------------------------------------------

CREATE SEQUENCE SEQ_CUSTOMERS
    START WITH 16   -- next after seed data
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_STAFFS
    START WITH 9
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_MENU_ITEMS
    START WITH 30
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_MENU_ITEM_PORTIONS
    START WITH 66
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_PAYMENTS
    START WITH 13
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ORDERS
    START WITH 13
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ORDER_ITEMS
    START WITH 16
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_DELIVERIES
    START WITH 11
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_EVENTS
    START WITH 6
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;